import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import { VitePWA } from 'vite-plugin-pwa'

/**
 * The offline story has two halves, and only one of them is a build concern.
 *
 * 1. THE APP SHELL. A service worker is emitted into the *production build*
 *    only. `npm run dev` therefore has no service worker at all, which is why
 *    offline appears "broken" while developing — nothing is cached because
 *    nothing has been built. `npm run offline` builds and serves the real
 *    thing; `npm run dev:offline` turns the worker on in dev for testing.
 *
 * 2. THE VOICE MODEL. Weights are fetched from the Hugging Face Hub on an
 *    explicit user download and cached by the browser, so voice keeps working
 *    with no signal afterwards. SeePat pays no bandwidth for this and the
 *    owner pays nothing for it, which is why it sits in the free tier.
 *
 * Both must be reachable with no network for the offline claim to be true, so
 * each cache is declared here rather than left to chance.
 */
export default defineConfig(({ mode }) => ({
  plugins: [
    react(),
    tailwindcss(),
    VitePWA({
      registerType: 'autoUpdate',
      // `icon.svg` is deliberately NOT listed here: it is declared in
      // `manifest.icons` below, which already adds it to the precache, and
      // listing it in both places made the worker carry it twice.
      includeAssets: [],
      manifest: {
        // `id` pins the installed app's identity. Without it the identity is the
        // start_url, and changing that URL later installs a *second* app beside
        // the first instead of updating it.
        id: '/',
        name: 'SeePat — Ang Financial Copilot ng Negosyo',
        short_name: 'SeePat',
        description:
          'Voice-enabled, explainable financial decision copilot for Filipino microentrepreneurs.',
        lang: 'fil',
        categories: ['finance', 'business', 'productivity'],
        // Both match the page canvas, not the brand navy. The header is a light
        // translucent bar, so a navy status bar on top of it reads as a seam;
        // these values make the splash screen and the Android status bar
        // disappear into the app instead of framing it.
        theme_color: '#f5f7fb',
        background_color: '#f5f7fb',
        display: 'standalone',
        orientation: 'portrait',
        start_url: '/',
        /*
         * WHY THERE ARE PNG ICONS, AND WHY IT IS NOT COSMETIC:
         *
         * Chrome only offers "Install app" when the manifest declares a PNG icon
         * of at least 144px. An SVG entry is accepted by the manifest parser and
         * ignored by the installability check, so a manifest whose only icon is
         * an SVG looks perfectly correct in devtools and never installs. That was
         * the bug.
         *
         * `maskable` gets its own entry rather than sharing one with `any`: a
         * rounded tile declared as maskable has its corners shaved by Android, so
         * the safe-zone padding has to be baked into a separate file (both are
         * generated by `node tools/make-assets.mjs`).
         */
        icons: [
          { src: 'pwa-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
          { src: 'pwa-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
          { src: 'pwa-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
          // Kept last and as a fallback for anything that prefers the vector.
          { src: 'icon.svg', sizes: 'any', type: 'image/svg+xml', purpose: 'any' },
        ],
      },
      workbox: {
        // png is here for the wordmark: it is part of the app shell, so a stale
        // cache would leave the header with a broken image offline.
        globPatterns: ['**/*.{js,css,html,svg,png,woff2}'],
        /*
         * What ends up in the precache, and why — because the interesting part
         * here is NOT what the config says but what the generated worker does.
         *
         * vite-plugin-pwa adds every `manifest.icons` entry to the precache as an
         * additional manifest entry, independently of the glob. So a declared
         * icon is precached whether or not it matches `globPatterns` — and if it
         * matches as well, the worker lists it TWICE (measured: 20 entries for 16
         * files, and Workbox warns about duplicates). Listing them in
         * `globIgnores` is therefore the correct thing to do, not to exclude them
         * but to stop the glob pass duplicating what the manifest already
         * declared.
         *
         * Net effect, verified against the generated sw.js:
         *  - pwa-192 / pwa-512 / pwa-maskable-512: precached once each, and that
         *    is right — the platform re-reads the icon when the app is launched
         *    from the home screen, where "no signal" is this product's normal
         *    condition.
         *  - og-image.png (72KB) and apple-touch-icon.png: excluded. A social card
         *    is fetched by crawlers, and the iOS icon is captured when the user
         *    adds the app, so neither is ever needed to paint the interface.
         *  - seepat-wordmark.png stays: the header renders it.
         *
         * `icon.svg` gets the same treatment for the same reason: it is both
         * globbed and declared, so the worker mentioned it twice.
         */
        globIgnores: [
          '**/offline-voice-*.js',
          // Declared in `manifest.icons`, which already adds them — see below.
          'og-image.png',
          'pwa-*.png',
          'apple-touch-icon.png',
          'icon.svg',
        ],
        // The on-device runtime (ONNX Runtime + transformers) is large and is
        // only ever fetched by an owner who picks "download for offline". It is
        // runtime-cached below instead, so precaching does not charge everyone
        // for a feature most free users will never open.
        navigateFallback: '/index.html',
        maximumFileSizeToCacheInBytes: 4 * 1024 * 1024,
        runtimeCaching: [
          // NOTE: there is deliberately no rule for huggingface.co. The library
          // already persists model weights in its own Cache Storage bucket, and
          // a second CacheFirst rule for the same responses stores every weight
          // twice — measured at 41.6MB duplicated, which is real money on a
          // Philippine mobile plan. Let the library own its own cache; this file
          // only caches what the library does not.
          {
            // ONNX Runtime's WASM binaries. Bundling resolves these to our own
            // origin, so the rule matches by extension rather than by host —
            // without it the runtime is re-fetched on every reload and offline
            // voice dies the moment the network goes away, which is the exact
            // failure this whole file exists to prevent.
            urlPattern: /\.wasm(\?.*)?$/i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'wasm-runtime',
              expiration: { maxEntries: 16, maxAgeSeconds: 60 * 60 * 24 * 365 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
          {
            // Safety net: transformers.js falls back to a CDN for WASM paths
            // in some setups. Cache it if it ever happens.
            urlPattern: /^https:\/\/(cdn|fastly)\.jsdelivr\.net\//i,
            handler: 'CacheFirst',
            options: {
              cacheName: 'onnx-runtime-cdn',
              expiration: { maxEntries: 24, maxAgeSeconds: 60 * 60 * 24 * 365 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
          {
            // Anything this app actually loaded once stays available offline:
            // that is the whole point of an offline-first ledger.
            urlPattern: ({ request }: { request: Request }) =>
              request.destination === 'script' || request.destination === 'style',
            handler: 'CacheFirst',
            options: {
              cacheName: 'app-assets',
              expiration: { maxEntries: 64, maxAgeSeconds: 60 * 60 * 24 * 30 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
        ],
      },
      devOptions: {
        // Off by default: a stale dev cache is a confusing dev cache.
        enabled: mode === 'pwadev',
        type: 'module',
      },
    }),
  ],
  build: {
    rollupOptions: {
      output: {
        manualChunks(id: string) {
          if (id.includes('@huggingface/transformers') || id.includes('onnxruntime')) {
            return 'offline-voice'
          }
          return undefined
        },
      },
    },
  },
}))
